### ISSUE TITLE
Please support Windows

### ISSUE THREAD

**Issue by moorepants** [conda-forge/ipopt-feedstock#1]

**Comment by pstjohn** [comment]
I don't have much in the way of experience writing windows batch files, especially for conda..
Hopefully this would get addressed at some point, however, I know there are some existing build scripts for the windows binaries around

**Comment by moorepants** [comment]
I noticed that someone has built a bunch of the x-org libs using some MSYS2 conda-forge tools. Maybe the IPopt stack can copy them. For example: https://github.com/conda-forge/xorg-libxi-feedstock.

**Comment by richardotis** [comment]
I'm concerned we may be dead in the water on this, so I wanted to post what I've learned so far in the hopes that someone else may see a path forward. MUMPS, the only permissively licensed linear solver for IPOPT, seems to [require the Intel Fortran compiler on Windows](http://mumps.enseeiht.fr/index.php?page=links). This is a problem since the Intel Fortran compiler is proprietary.

I think this means we have to go the semi-supported MinGW/MSYS route, but will this break binary compatibility with our Python, which we must assume was compiled with MSVC on Windows?

**Comment by richardotis** [comment]
Other problems: MUMPS dependencies scotch ([in-progress Windows support](https://github.com/conda-forge/scotch-feedstock/pull/8)) and METIS (complete Windows support) both use MSVC for their builds.

**Comment by bluescarni** [comment]
@richardotis There is a nice summary of the MinGW/Python situation here:

https://mingwpy.github.io/motivation.html
https://mingwpy.github.io/issues.html

I have built and used MinGW-compiled Python extensions together with vanilla Python for Windows for quite some time now, and have not run in practical issues despite the warnings mentioned in the links above (MinGW is still the only practical choice on windows for C++ code relying on robust C++11 support, which MSVC still does not have).

The biggest potential issue is that when you mix MSVC-compiled code with MinGW-compiled code, you are bringing two separate C runtimes (or C standard libraries, as they are called on Unix) into the same program. This will create issues if, for instance, you invoke one stdlib's ``malloc()`` and later free the memory with the other stdlib's ``free()``. If you are working with C++, there are additional issues related, e.g., to exception handling and ABI - but I don't think they apply to Ipopt, as we would not be mixing C++ code compiled with different compilers.

If I understood correctly, the plan for Ipopt on windows would be to use gfortran to compile mumps and then link to it from an MSVC-compiled Ipopt, assuming the binary interfaces are compatible. Linking to mumps would bring in the MinGW C runtime, and we would then need to test that the two runtimes are properly insulated from each other.

I am not sure what the status is regarding MinGW support in conda-forge, nor I have a clear idea what kind of hackery would be needed in the Ipopt build system though...

**Comment by richardotis** [comment]
Relevant issues: https://github.com/Microsoft/vcpkg/issues/233 https://github.com/Microsoft/vcpkg/issues/485#issuecomment-270219347

Looks like it may be possible to use MSVC and gfortran together via CMake: https://cmake.org/cmake/help/v3.7/prop_tgt/GNUtoMS.html http://www.netlib.org/lapack/lawnspdf/lawn270.pdf

Other possibility, Fortran 90 to C conversion (no idea if it will work better than f2c): http://cci.lbl.gov/fable/

**Comment by chrisdembia** [comment]
I'm also looking to find a way to build Ipopt on Windows using Visual Studio with MUMPS compiled with gfortran.

**Comment by richardotis** [comment]
Not sure how the rest of the conda forge community would feel about this, but shipping pre-built ipopt binaries on Windows looks pretty tempting: https://anaconda.org/cachemeorg/ipopt_bin/files

What does everyone think?

**Comment by moorepants** [comment]
I think it is fine if conda forge allows you to upload binaries that aren't built with conda forge.

Also, i noticed that SciPy 1.0 will be able to be built with openblas, MSVC, and gfortran in the versions release notes. Seems like whatever solution they have going might be something useful for getting the core dependencies going on on conda forge.

**Comment by richardotis** [comment]
PR implementing this idea: #11

**Comment by richardotis** [comment]
I've made significant progress getting ipopt to build on Windows using `m2w64-toolchain` and several other pieces of MSYS2. This requires MUMPS (see https://github.com/conda-forge/mumps-feedstock/pull/17#issuecomment-345535745 ) but not SCOTCH. No conda build yet, but the build is tricky, so I wanted to document what I've done so far here. Starting from a conda environment with `m2w64-toolchain`, `m2w64-openblas` and `posix` packages from msys2 channel installed, in the Ipopt-3.12.8 source directory:
```
conda install --use-local mumps # must build mumps according to above comment
rm /mingw-w64/bin/make.exe # should not do anything unless you are repeating these steps
bash -c "CXXDEFS=-DCOIN_USE_MUMPS_MPI_H ADD_CXXFLAGS='-I/include -L/lib' ./configure --build=x86_64-w64-mingw32 --disable-linear-solver-loader --with-blas-lib='-lopenblas' --with-mumps-lib='-ldmumps -lmumps_common -lpord -lgfortran' --enable-shared --enable-dependency-linking" # be prepared to wait 5 minutes or so
cp /mingw-w64/bin/mingw32-make.exe /mingw-w64/bin/make.exe
mingw32-make clean
mingw32-make test # be prepared to wait 30 minutes or more; verify tests pass
rm /mingw-w64/bin/make.exe
```
I'm still having trouble getting a statically-linked ipopt.dll to build.

**Comment by richardotis** [comment]
Current trouble with DLL building:
```
*** Warning: linker path does not have real file for library -ldmumps.
*** I have the capability to make that library automatically link in when
*** you link to this library.  But I can only do this if you have a
*** shared version of the library, which you do not appear to have
*** because I did check the linker path looking for a file starting
*** with libdmumps and none of the candidates passed a file format test
*** using a file magic. Last file checked: /bin/libdmumps.dll.a

*** Warning: linker path does not have real file for library -lopenblas.
*** I have the capability to make that library automatically link in when
*** you link to this library.  But I can only do this if you have a
*** shared version of the library, which you do not appear to have
*** because I did check the linker path looking for a file starting
*** with libopenblas and none of the candidates passed a file format test
*** using a file magic. Last file checked: /mingw-w64/bin/libopenblas.dll
*** The inter-library dependencies that have been dropped here will be
*** automatically added whenever a program is linked with this library
*** or is declared to -dlopen it.

*** Since this library must not contain undefined symbols,
*** because either the platform does not support them or
*** it was explicitly requested with -no-undefined,
*** libtool will only create a static version of it.
```

**Comment by moorepants** [comment]
It may be worth asking about these issues on the IPOPT mailing list.

**Comment by richardotis** [comment]
Having some luck with this make rule added to `Ipopt-3.12.8\src\Interfaces\Makefile` ( https://list.coin-or.org/pipermail/ipopt/2013-August/003477.html ):
```
libipopt.dll: $(libipopt_la_OBJECTS) $(libipopt_la_DEPENDENCIES)
	$(CXXLINK) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -static -shared -o $@ \
-Wl,-rpath,$(libdir) $(libipopt_la_LDFLAGS) $(libipopt_la_OBJECTS) -lipopt -ldmumps -lmumps_common -lopenblas -lgfortran
```
I can compile a DLL and link it to a test problem, but now I'm working through some runtime missing DLL errors.

**Comment by richardotis** [comment]
A `make clean` seems to have solved it. I copied the libipopt.dll to the `Ipopt-3.12.8\test` folder, ran `mingw32-make clean` from the main folder to remove any static build artifacts, then ran `gcc -o hs071_c.exe hs071_c.c -I../src/Interfaces/ -L. -lipopt` and then `hs071_c.exe`. The resulting test problem runs and converges to the solution.

The next steps are to pull all of these steps into a reproducible build script.

**Comment by richardotis** [comment]
I can't quite figure out how to get patching to work properly in conda build, and the paths are not entirely correct yet, but here are my WIP recipes for ipopt and mumps:
https://github.com/richardotis/ipopt-feedstock/tree/windows_support
https://github.com/richardotis/mumps-feedstock/tree/windows_support

In principle, all you need to do is add msys2 channel and run `conda build .` inside the feedstock directory. (You have to build mumps and then install it with `--use-local`, before ipopt.) The reality right now is the patching machinery doesn't seem to work quite right on my Windows machine (CRLF issue?), and so I'll need some help with (a) getting the CMakeLists.txt in the recipe directory into the mumps source root at build time, and (b) getting the ipopt dll_makefile.patch to apply cleanly.

**Comment by richardotis** [comment]
https://github.com/richardotis/ipopt-feedstock/tree/ab2834339620425b9014c7fc9066af4a365d9055
https://github.com/richardotis/mumps-feedstock/tree/3c1a8e6bc78d0b33fae65cf4d2fe07ed5bb3af87

These are ready for a look. It should be as easy as adding msys2 to your list of channels and then `conda build .` in the mumps directory, followed by `conda build .`. I think you don't need to `conda install` mumps at all as long as the built package is in your build cache.

**Comment by tkelman** [comment]
You really shouldn't disable the linear solver loader, and it can build fine with mingw. That's a pretty important feature given the licensing of the various linear solvers ipopt can use.

**Comment by corentinmartinon** [comment]
Hi everyone. Trying to link an application with ipopt on windows I noticed that the windows libraries are a bit old (VS2010).
There seem to be more recent ones here: https://github.com/coin-or/Ipopt/releases/tag/releases%2F3.13.2
These are built with VS2019 and they appear to work fine (they are dynamic libs however unlike the current static ones)
Would it be possible to update the windows package here with these somehow ?
