### ISSUE TITLE
Ipopt 3.12.9  for  Win64

### ISSUE THREAD

**Issue by maajdl** [conda-forge/ipopt-feedstock#17]
Hello,

I don't know how conda works, I only know how to use conda from my Jypiter notebooks!
Sorry for my naive question, but maybe this is here the place to ask.

I have been using Pyomo/Ipopt 3.11  on Win64  for a year now.
I recently tumbled on a bug that seems to be related to Ipopt 3.11 (memory leak), and I was advised to switch  to Ipopt 3.12  ([https://github.com/Pyomo/pyomo/issues/399](https://github.com/Pyomo/pyomo/issues/399)) .

Unfortunately, I could not find the 3.12  version on [anaconda.org/conda-forge/ipopt](anaconda.org/conda-forge/ipopt), where I had found  version 3.11 earlier.
After investigation, I had the impression that I would not be able to compile it by myself.

In case I would give it a try anyway to build a win64 version, could you give me a few directions, some (easy) reading?

In case that would be too time consuming for beginners, what would be the chances to get a Win64 version sometimes?

Thanks!

Michel

**Comment by pstjohn** [comment]
So the previous windows version just wrapped the binary download options from the main ipopt website (see #11). But for various reasons I think we stopped using that option. You might be better off just looking around to see if there's a win64 binary for ipopt in the version you want?

**Comment by richardotis** [comment]
A few months ago I built win64 packages for ipopt 3.12 and its dependencies: https://anaconda.org/pycalphad

At the time I had to use a custom channel because I built using msys2, but now that it's been added to defaults it's probably possible to port the recipes to conda-forge. I started some of that work in https://github.com/conda-forge/mumps-feedstock/pull/25 but I haven't had time to run all the issues to ground yet.

**Comment by maajdl** [comment]
I had a look at pycalphad.
Unfortunately, Pyomo needs an .exe file for Ipopt.
It seems  you are using a .dll file for pycalphad.
Could the dll be used somehow as an .exe too ?

In also found a Win64 Ipopt 3.12 on the AMPL site.
I also get exceptions with this version, but in other situations (that worked nicely with 3.11).
Can't figure out if the bug could be in Ipopt or Pyomo.
I would need to look at the right place in Pyomo to be sure.

Finally, I tested three version: 3.10, 3.11, 3.12, and had problem with all of them.
But all in all  3.11 seem now the easiest to work with.
Anyway, I am very happy with Ipopt, even  if some models trigger exceptions.

**Comment by richardotis** [comment]
Cleaned up what I had and submitted #18 - you're right that it isn't building ipopt.exe at the moment, that should probably be addressed.
