### ISSUE TITLE
MKL dependency issue

### ISSUE THREAD

**Issue by whart222** [conda-forge/ipopt-feedstock#22]
Issue:  I'm having trouble installing this recipe on OSX with anaconda.  The error appears to be related to the defaults dependency on MKL.  Is it possible to create IPOPT builds with this dependency?

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by pstjohn** [comment]
It's not possible (i believe) to link against MKL in a conda-forge feedstock. So we use openblas instead, which might lead to the error. What specific error are you getting? What package do you need mkl for?
