### ISSUE TITLE
Compile with clang on OSX?

### ISSUE THREAD

**Issue by moorepants** [conda-forge/ipopt-feedstock#3]
I'm creating a cyipopt feedstock and I just had [this conversation](https://github.com/conda-forge/staged-recipes/pull/2273#discussion_r98334217) with @ocefpaf about whether gcc or clang should be used for the OSX builds. He mentioned possibilities of incompatibilities with other packages on conda-forge. The ipopt feedstock is compiled with gcc and cyipopt uses pkg-config to get the correct linker flags and it picks up `-lgcc_eh` from this build. This isn't compatible with clang. I'm not sure what `gcc_eh` is exactly or how that interplays with a clang compilation. Some questions:

1. Did you try to build ipopt with clang?
2. Should we be building with clang?
3. Should I be building cyipopt with clang even though ipopt is bulit with gcc (I can abandon the pkg-config based installation.)

**Comment by pstjohn** [comment]
So it looks like there's already a cyipopt feedstock? Was that built using the gcc version?

Honestly I hadn't tried using clang, I was sortof in the same boat of trying to maintain compatibility with the tools that came beforehand. (See, for instance, conda-forge/mumps-feedstock). @basnijholt might be able to weigh in on why gcc?

**Comment by moorepants** [comment]
I just created the cyipopt feedstock, it was just merged.. Currently it uses gcc on OSX. But @ocefpaf seemed to indicate that clang is preferred in Conda Forge. I don't understand the consequences, but if it were to change to clang it seems we have to dig further into the dependency stack.

**Comment by bluescarni** [comment]
I have reported an issue related to the clashing of the standard libraries of clang and gcc in #5 (along with a possible solution).

**Comment by moorepants** [comment]
Fixed by #5.
