### ISSUE TITLE
Avoiding relying on a coinor-cmake fork for Ipopt 3.13.3 

### ISSUE THREAD

**Issue by traversaro** [conda-forge/ipopt-feedstock#51]
In https://github.com/conda-forge/ipopt-feedstock/pull/47 support for compilation on Windows was added using a fork of the coinor-cmake repo (https://github.com/ycollet/coinor-cmake) with modifications for Ipopt 3.13.3 (https://github.com/ycollet/coinor-cmake/issues/11) . When the upstream coinor-cmake will support Ipopt 3.13.3, we should stop relying on a fork and switch back to use the upstream coinor-cmake repo.

**Comment by jschueller** [comment]
can you send a pull-request ?

**Comment by moorepants** [comment]
> can you send a pull-request ?

Pull request to what?

**Comment by jschueller** [comment]
to ycollet/coinor-cmake, but this was for @traversaro

**Comment by traversaro** [comment]
> 
> 
> can you send a pull-request ?

I already notified upstream inhttps://github.com/ycollet/coinor-cmake/issues/11 . Opening directly a pull request is tricky as coinor-cmake also covers many other coinor projects (and I fixed the build just of Ipopt) and the project is in a temporary hiatus due to the many changes in the coinor projects, see  the warning at the top of the README: https://github.com/ycollet/coinor-cmake#coinor-cmake .
