### ISSUE TITLE
ipopt.pc file is not generated correctly for all platforms

### ISSUE THREAD

**Issue by moorepants** [conda-forge/ipopt-feedstock#56]
Issue:

IPOPT supplies a .pc file for use with pkg-config. It resides in `$PREFIX/Library/lib/pkg-confg/ipopt.pc` in the Windows build tarball. The contents are:

```
prefix=D:/bld/ipopt_1605616866017/_h_env/Library
prefix=${pcfiledir}/../..
exec_prefix=${prefix}
libdir=D:/bld/ipopt_1605616866017/_h_env/Library/lib
includedir=D:/bld/ipopt_1605616866017/_h_env/Library/include/coin-or

Name: IpOpt
Description: Interior Point Optimizer
URL: 
Version: 3.13.3
Cflags: -I${includedir}
Libs: -L${libdir} -lipopt
Requires.private:  -llapack
Libs: -L${libdir} -lipopt -lm -ldl
Requires:  -llapack
```

Some notes:

- `prefix` is defined twice
- The build directory is hard coded. Does `conda install` typically fix these paths? Does it do it in `.pc` files? Are those hard coded paths sufficient for conda to search and replace them?
- the -lipopt flags are hard coded from upstream IPOPT, but for windows the libraries are named `ipopt-3`

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by moorepants** [comment]
The source code for IPOPT has `ipopt.pc.in` which is a template file for the final `ipopt.pc` that is built. It looks like:

```
@COIN_RELOCATABLE_FALSE@prefix=@prefix@
@COIN_RELOCATABLE_TRUE@prefix=${pcfiledir}/../..
exec_prefix=@exec_prefix@
libdir=@libdir@
includedir=@includedir@/coin-or

Name: @PACKAGE_NAME@
Description: Interior Point Optimizer
URL: @PACKAGE_URL@
Version: @PACKAGE_VERSION@
Cflags: -I${includedir}
@COIN_STATIC_BUILD_FALSE@Libs: -L${libdir} -lipopt
@COIN_STATIC_BUILD_FALSE@Requires.private: @IPOPTLIB_PCFILES@
@COIN_STATIC_BUILD_TRUE@Libs: -L${libdir} -lipopt @IPOPTLIB_LFLAGS_NOPC@
@COIN_STATIC_BUILD_TRUE@Requires: @IPOPTLIB_PCFILES@
```

It has two prefix definitions. But pkg-config produces a warning about that double definition.

**Comment by traversaro** [comment]
I suspect that the syntax:
~~~
@COIN_RELOCATABLE_FALSE@prefix=@prefix@
@COIN_RELOCATABLE_TRUE@prefix=${pcfiledir}/../..
~~~
means something special for the autotools build system, meaning that depending on the value of `COIN_RELOCATABLE_FALSE` or `COIN_RELOCATABLE_TRUE` only one of the two lines are included.

**Comment by moorepants** [comment]
Is it possible to set that in CMAKE so it is handled properly?

**Comment by moorepants** [comment]
I'm trying to figure out out to patch the `ipopt.pc` file so that it is correct. I can remove the second prefix definition easily, but I wasn't sure if the hardcoded build paths were correct.

**Comment by moorepants** [comment]
I see here https://docs.conda.io/projects/conda-build/en/latest/resources/make-relocatable.html that the hardcoded paths will be fixed because it is declared in the `info/has_prefix` file. So maybe only that second prefix needs to be removed.

**Comment by moorepants** [comment]
This `@COIN_STATIC_BUILD_FALSE@` is also not being honored with CMAKE.

**Comment by traversaro** [comment]
> 
> 
> Is it possible to set that in CMAKE so it is handled properly?

I don't think this can be done easily, `@<something>@` string are processed by CMake's [`configure_file`](https://cmake.org/cmake/help/latest/command/configure_file.html) with a different logic, namely that their content is substiute with the content of the the CMake variable `<something>`  is `<something>` is not defined, then they will just evaluate to the empty string, so the rest of the line will be left as it is.  Probably shipping a completely different .pc file or template file is easier.

**Comment by moorepants** [comment]
Ok. I'm trying out the custom pc file with cyipopt to see if I can get it working here: https://github.com/matthias-k/cyipopt/pull/78

**Comment by moorepants** [comment]
This is related: https://github.com/conda-forge/blas-feedstock/issues/58 conda-forge is not creating the blas and lapack pc files.

**Comment by traversaro** [comment]
> 
> 
> This is related: [conda-forge/blas-feedstock#58](https://github.com/conda-forge/blas-feedstock/issues/58) conda-forge is not creating the blas and lapack pc files.

I may be missing something, but if both ipopt and blas/lapack are compiled as shared library (as it is the case for ipopt in conda-forge) and ipopt public headers do not include blas/lapack public headers, for using ipopt there is no need to be do nothing w.r.t. blas/lapack. See for example the https://github.com/conda-forge/ipopt-feedstock/blob/fb4e438f37bcd6b2fe21429897459bbc0c342651/recipe/run_test.bat#L6 , in which ipopt is used by simply linking `ipopt-3.lib` .

**Comment by moorepants** [comment]
This issue is associated with whether `pkg-config --libs --cflags ipopt` works (on all platforms). The `.pc` files have to be properly defined for ipopt, lapack, blas and any other libs that are in that compile chain. I don't think that conda-forge blas/lapack or ipopt are creating and depositing the correct `.pc` files.

**Comment by moorepants** [comment]
For this feedstock, it doesn't seem like CMAKE is properly selecting the options in the `lapack.pc.in` file when generating `lapack.pc` and I'm not sure the compiler flags in the resulting `lapack.pc` are correct for windows. For example, it has `-lipopt` but shouldn't it be `-lipop-3`?

**Comment by traversaro** [comment]
>  For example, it has -lipopt but shouldn't it be -lipop-3?

Yes that is exact and this is the reason (among others) why the issue is open. 

> This issue is associated with whether `pkg-config --libs --cflags ipopt` works (on all platforms).

In that case I suggest to rename the title, that indicates instead that this issue is just related to Windows.

**Comment by traversaro** [comment]
>  The .pc files have to be properly defined for ipopt, lapack, blas and any other libs that are in that compile chain.

Why? As far as I understand, if the dependencies are not exposed in public headers and all the libraries are shared, the consume or ipopt library does not need to know that ipopt itself links to other libraries.

**Comment by moorepants** [comment]
I don't really know other than `pkg-config` no longer works with the conda-forge blas, lapack, and ipopt because `.pc` files are missing or not correctly defined.

**Comment by traversaro** [comment]
> 
> 
> I don't really know other than `pkg-config` no longer works with the conda-forge blas, lapack, and ipopt because `.pc` files are missing or not correctly defined.

I see, then I think that the easiest solution (from the ipopt side) is just to remove any reference to blas and lapack and everything should work. Anyway to validate this we can modify the tests compilation in run_tests.sh/run_tests.bat to use pkg-config instead of manually passing options.
