### ISSUE TITLE
Pin ipopt at the conda-forge level to enable the use of automatic ABI migrations?

### ISSUE THREAD

**Issue by traversaro** [conda-forge/ipopt-feedstock#68]
In https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/1652 I proposed to pin ipopt at the conda-forge level, so that we can automatically run ABI migrations once a new version of ipopt is released. I open this issue to give visibility to this change to people that are watching this repo.

**Comment by moorepants** [comment]
Does this simply mean that if ipopt is updated here, that PRs will be automatically made to any downstream dependencies in conda forge to build against the new ipopt? If so, that's fine with me.

**Comment by traversaro** [comment]
> Does this simply mean that if ipopt is updated here, that PRs will be automatically made to any downstream dependencies in conda forge to build against the new ipopt? If so, that's fine with me.

Exactly, however the PRs will be make only for ABI incompatible changes, i.e. in the IPOPT case for new minor releases, not for patch releases.

**Comment by jschueller** [comment]
resolved
