### ISSUE TITLE
CI for osx-arm64 build (#79) wasn't triggered

### ISSUE THREAD

**Issue by Tobias-Fischer** [conda-forge/ipopt-feedstock#80]

**Comment by Tobias-Fischer** [comment]
@traversaro - are you able to restart the CI on the main branch? It seems that the build for #79 wasn't triggered for some reason.

**Comment by traversaro** [comment]
I am not sure what happened, but I merged a new PR and now the job for the build seems to have been triggered: https://github.com/conda-forge/ipopt-feedstock/runs/5521289733 .

**Comment by traversaro** [comment]
osx-arm64 file has been uploaded: https://anaconda.org/conda-forge/ipopt/files .
